### ISSUE TITLE
Use isNan

### ISSUE THREAD

**Issue by cherifGsoul** [Fcmam5/algeria-api#2]
I would use [`isNan`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN) [here](https://github.com/Fcmam5/algeria-api/blob/develop/server/middlewares/index.js#L8) instead of `!matr`!

**Comment by Fcmam5** [comment]
Thank you very much @cherifGsoul, I'll fix it now
