### ISSUE TITLE
What is the difference between wilayas names in both languages french and english

### ISSUE THREAD

**Issue by gskamel** [Fcmam5/algeria-api#26]
Thank you for this work.

**Comment by Fcmam5** [comment]
Hi @gskamel Thank you!
For now, there's no difference between French and English names, I just set the field to update it later if we have wilayas who have different names like `Algiers/Alger`. I thought that maybe the other wilayas could have different names or just written without `é, ï ...`

But, if you think something else you are welcome to discuss it.
